In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[8.0, 7.0, 6.0],[5.0,4.0,3.0]], dtype='float32')
print(b)

[[8. 7. 6.]
 [5. 4. 3.]]


In [4]:
b.ndim

2

In [5]:
b.itemsize

4

In [6]:
x = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
x[1,5]

13

In [7]:
x[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [8]:
y = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(y)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
y.shape

(2, 2, 2)

In [10]:
y[:,1,:]

array([[3, 4],
       [7, 8]])

In [11]:
t = np.zeros((2,3,3,2))
print(t)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [15]:
h = np.full((4,3), 67)
print("shape of h: ", h.shape)
print(h)

shape of h:  (4, 3)
[[67 67 67]
 [67 67 67]
 [67 67 67]
 [67 67 67]]


In [16]:
g = np.full_like(h, 32)
print(g)

[[32 32 32]
 [32 32 32]
 [32 32 32]
 [32 32 32]]


In [17]:
p = np.random.rand(4, 2)
print(p)

[[0.23292198 0.44778541]
 [0.38531346 0.12518921]
 [0.81350178 0.71983465]
 [0.2541418  0.77420132]]
